-- RUN THIS SQL IN YOUR SUPABASE SQL EDITOR TO ADD USERBOT PROFILE FIELDS
ALTER TABLE userbots ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE userbots ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE userbots ADD COLUMN IF NOT EXISTS groups_count INTEGER DEFAULT 0;
